from github_client import GitHubClient
from ollama_client import OllamaClient
from config import Config
import re

class PRCreator:
    def __init__(self):
        self.github = GitHubClient()
        self.ollama = OllamaClient()
    
    def create_fix_pr(self, issue, fixes, analysis):
        """Complete flow: branch → commit → PR"""
        
        if not fixes:
            print(f"❌ No fixes generated for issue #{issue['number']}")
            return None
        
        # 1. Create branch name
        branch_name = self._generate_branch_name(issue)
        print(f"🌿 Creating branch: {branch_name}")
        
        # 2. Create the branch
        if not self.github.create_branch(branch_name):
            return None
        
        # 3. Commit each fixed file
        changes_summary = []
        for file_path, file_data in fixes.items():
            commit_msg = f"fix: address issue #{issue['number']} in {file_path}"
            
            success = self.github.commit_file(
                file_path=file_path,
                new_content=file_data['fixed'],
                commit_message=commit_msg,
                branch_name=branch_name
            )
            
            if success:
                changes_summary.append(f"- Modified `{file_path}`")
        
        # 4. Generate PR description using Ollama
        changes_text = "\n".join(changes_summary)
        pr_body = self.ollama.generate_pr_description(issue, changes_text)
        
        # Add standard footer
        pr_body += f"\n\n---\n> 🤖 Auto-generated by GitHub Agent\n> Fixes #{issue['number']}"
        
        # 5. Create the Pull Request
        pr = self.github.create_pull_request(
            title=f"fix: {issue['title']} (#{issue['number']})",
            body=pr_body,
            branch_name=branch_name
        )
        
        return pr
    
    def _generate_branch_name(self, issue):
        """Create a clean branch name from issue"""
        # Clean the title
        clean_title = issue['title'].lower()
        clean_title = re.sub(r'[^a-z0-9\s-]', '', clean_title)
        clean_title = re.sub(r'\s+', '-', clean_title.strip())
        clean_title = clean_title[:40]  # Limit length
        
        return f"{Config.BRANCH_PREFIX}/issue-{issue['number']}-{clean_title}"