# agents/pr_manager.py

import re
from core.base_agent import BaseAgent
from typing import Dict
from config.settings import Config

class PRManagerAgent(BaseAgent):
    """
    Creates Pull Requests with all the fixes
    """
    
    def __init__(self):
        super().__init__(
            name="pr_manager",
            description="Creates and manages Pull Requests"
        )
        self.capabilities = ["create_pr", "manage_branches"]
    
    def can_handle(self, task: Dict) -> bool:
        return task.get('type') == 'create_pr'
    
    async def execute(self, task: Dict) -> Dict:
        issue = task.get('issue')
        fixes = task.get('fixes', {})
        tests = task.get('tests', {})
        analysis = task.get('analysis', {})
        
        self.logger.info(f"Creating PR for issue #{issue['number']}")
        
        # Create branch
        branch_name = self._create_branch_name(issue)
        
        if not self.github.create_branch(branch_name):
            return {"success": False, "error": "Failed to create branch"}
        
        # Commit all fixes
        committed_files = []
        all_changes = {**fixes, **tests}  # Combine fixes and tests
        
        for file_path, file_data in all_changes.items():
            content = file_data if isinstance(file_data, str) else file_data.get('fixed', '')
            
            success = self.github.commit_file(
                file_path=file_path,
                new_content=content,
                commit_message=f"fix(#{issue['number']}): {file_path}",
                branch_name=branch_name
            )
            
            if success:
                committed_files.append(file_path)
        
        if not committed_files:
            return {"success": False, "error": "No files committed"}
        
        # Generate PR description
        pr_body = await self._generate_pr_body(issue, analysis, committed_files, tests)
        
        # Create the PR
        pr = self.github.create_pull_request(
            title=f"🤖 fix(#{issue['number']}): {issue['title'][:60]}",
            body=pr_body,
            branch_name=branch_name,
            base_branch="main"
        )
        
        if pr:
            self.logger.info(f"✅ PR created: {pr.html_url}")
            return {
                "issue": issue,
                "pr": {"number": pr.number, "url": pr.html_url},
                "files_changed": committed_files,
                "branch": branch_name
            }
        
        return {"success": False, "error": "Failed to create PR"}
    
    async def _generate_pr_body(
        self, 
        issue: Dict, 
        analysis: Dict, 
        files: list, 
        tests: Dict
    ) -> str:
        """Generate a comprehensive PR description"""
        
        prompt = f"""Write a professional GitHub PR description for this fix.

ISSUE: #{issue['number']} - {issue['title']}
ISSUE BODY: {issue['body'][:500]}
ANALYSIS: {analysis.get('approach', 'Fixed the reported issue')}
FILES CHANGED: {', '.join(files)}
TESTS ADDED: {', '.join(tests.keys()) if tests else 'None'}

Format:
## 🎯 Summary
(what was fixed)

## 🔧 Changes Made
(bullet points of changes)

## 🧪 Testing
(how to test)

## ⚠️ Notes
(any important notes)

---
*🤖 Auto-generated by GitHub Agent System*
*Closes #{issue['number']}*"""
        
        messages = [
            {
                "role": "system",
                "content": "Write clear, professional PR descriptions in markdown."
            },
            {"role": "user", "content": prompt}
        ]
        
        return self.ollama.chat(messages, temperature=0.4)
    
    def _create_branch_name(self, issue: Dict) -> str:
        """Create a clean branch name"""
        title = issue['title'].lower()
        title = re.sub(r'[^a-z0-9\s-]', '', title)
        title = re.sub(r'\s+', '-', title.strip())[:40]
        return f"auto-fix/issue-{issue['number']}-{title}"